### ISSUE TITLE
errors in devstats-provision-*, devstats-grafana-*, devstats-prometheus-* pods during helm install

### ISSUE THREAD

**Issue by utako** [cncf/devstats-helm-example#3]
Hi again,

After following the EKS and DNS steps, I've `helm install ./devstats-helm-example --debug` with the following values.yml. I changed domainName, bootstrapCommand, projectsFile and provisionCommand:

```
affiliations: 'github_users.json'
bootstrapCommand: './devel/deploy_all.sh'
bootstrapLDrop: ''
bootstrapNoCreate: ''
bootstrapPodName: devstats-provision-bootstrap
bootstrapRestartPolicy: Never
bootstrapUDrop: ''
companyAcq: "companies.yaml"
concurrencyPolicy: Forbid
domainName: 'devstats.cncf-utako.routing.lol'
fullnameOverride: devstats
grafanaCommand: 'grafana_start.sh'
grafanaImage: 'lukaszgryglicki/devstats-grafana'
grafanaMaxSurge: 1
grafanaMaxUnavailable: 1
grafanaNReplicas: 2
grafanaPodName: devstats-grafana
grafanaPort: 3000
grafanaRestartPolicy: Always
grafanaSecret: grafana-secret
imagePullPolicy: Always
indexCronsFrom: 0
indexCronsTo: 100
indexGrafanasFrom: 0
indexGrafanasTo: 100
indexIngressesFrom: 0
indexIngressesTo: 100
indexProvisionsFrom: 0
indexProvisionsTo: 100
indexPVsFrom: 0
indexPVsTo: 100
indexServicesFrom: 0
indexServicesTo: 100
limitsBootstrapCPU: '2000m'
limitsBootstrapMemory: '2Gi'
limitsCronsCPU: '6000m'
limitsCronsMemory: '16Gi'
limitsGrafanasCPU: '2000m'
limitsGrafanasMemory: '8Gi'
limitsPostgresCPU: '8000m'
limitsPostgresMemory: '16Gi'
limitsProvisionsCPU: '8000m'
limitsProvisionsMemory: '16Gi'
name: devstats
nameOverride: devstats
oauthSecret: github-oauth
pgSecret: pg-db
proivisionImage: 'lukaszgryglicki/devstats'
projectsFile: 'projects.yaml'
provisionCommand: './devel/deploy_all.sh'
provisionPodName: devstats-provision
provisionRestartPolicy: Never
postgresSvcName: 'devstats-postgres'
postgresImageName: 'lukaszgryglicki/devstats-patroni'
postgresStorageSize: '100Gi'
postgresNodes: 3
pvName: devstats-pvc
requestsBootstrapCPU: '200m'
requestsBootstrapMemory: '256Mi'
requestsCronsCPU: '1000m'
requestsCronsMemory: '2Gi'
requestsGrafanasCPU: '300m'
requestsGrafanasMemory: '512Mi'
requestsPostgresCPU: '2000m'
requestsPostgresMemory: '4Gi'
requestsProvisionsCPU: '1000m'
requestsProvisionsMemory: '2Gi'
secretType: Opaque
servicePodName: devstats-service
storageAccessModes: ReadWriteOnce
storageClass: default
skipTemp: 1
syncCommand: devstats
syncImage: 'lukaszgryglicki/devstats-minimal'
syncPodName: devstats
syncRestartPolicy: Never
testsImage: 'lukaszgryglicki/devstats-test'
testsPodName: devstats-tests
testsRestartPolicy: Never
volumeMountName: data
volumeMountPath: '/root'
volumeName: data
useFlags: ''
useBootstrapResourcesLimits: 1
useCronsResourcesLimits: 1
useGrafanasResourcesLimits: 1
useProvisionsResourcesLimits: 1
usePostgresResourcesLimits: 1
waitForBootstrap: 60
waitForPostgres: 15
projects:
  - proj: cncf
    db: cncf
    icon: 'cncf'
    org: 'CNCF'
    repo: 'cncf/landscapeapp'
    cron: '25 * * * *'
    disk: 30Gi
    i: 0
  - proj: prometheus
    db: prometheus
    icon: 'prometheus'
    org: 'Prometheus'
    repo: 'prometheus/prometheus'
    cron: '10 * * * *'
    disk: 10Gi
    i: 1
  - proj: kubeflow
    db: kubeflow
    icon: 'kubeflow'
    org: 'Kubeflow'
    repo: 'kubeflow/kubeflow'
    cron: '40 * * * *'
    disk: 10Gi
    i: 2
```

One grafana failure:
```
$ kubectl describe pod devstats-grafana-cncf-b7f7c8446-p6hl9
Name:               devstats-grafana-cncf-b7f7c8446-p6hl9
Namespace:          devstats
Priority:           0
PriorityClassName:  <none>
Node:               ip-192-168-13-57.us-east-2.compute.internal/192.168.13.57
Start Time:         Thu, 16 May 2019 11:09:04 -0700
Labels:             name=devstats
                    pod-template-hash=b7f7c8446
                    proj=cncf
                    type=grafana
Annotations:        <none>
Status:             Running
IP:                 192.168.10.157
Controlled By:      ReplicaSet/devstats-grafana-cncf-b7f7c8446
Containers:
  devstats-grafana-cncf:
    Container ID:  docker://79b867f0be4ecdbce8c745bc50846e73347c3b788bdc67cc689022bfcc03587a
    Image:         lukaszgryglicki/devstats-grafana
    Image ID:      docker-pullable://lukaszgryglicki/devstats-grafana@sha256:92e66e47223337c522e9477b8fe4f507ae81e00b9e2b307d5b36f766ffbb57b3
    Port:          3000/TCP
    Host Port:     0/TCP
    Command:
      grafana_start.sh
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    6
      Started:      Thu, 16 May 2019 11:12:39 -0700
      Finished:     Thu, 16 May 2019 11:13:12 -0700
    Ready:          False
    Restart Count:  4
    Limits:
      cpu:     2
      memory:  8Gi
    Requests:
      cpu:      300m
      memory:   512Mi
    Liveness:   exec [grafana_health_check.sh 127.0.0.1:3000] delay=60s timeout=1s period=30s #success=1 #failure=3
    Readiness:  exec [grafana_health_check.sh 127.0.0.1:3000] delay=10s timeout=1s period=30s #success=1 #failure=3
    Environment:
      ICON:                        cncf
      ORGNAME:                     CNCF
      PROJ:                        cncf
      PG_DB:                       cncf
      PG_PORT:                     5432
      PG_HOST:                     <set to the key 'PG_HOST_RO.secret' in secret 'pg-db'>                           Optional: false
      PG_PASS:                     <set to the key 'PG_PASS_RO.secret' in secret 'pg-db'>                           Optional: false
      GF_SECURITY_ADMIN_USER:      <set to the key 'GF_SECURITY_ADMIN_USER.secret' in secret 'grafana-secret'>      Optional: false
      GF_SECURITY_ADMIN_PASSWORD:  <set to the key 'GF_SECURITY_ADMIN_PASSWORD.secret' in secret 'grafana-secret'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-92jxl (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-92jxl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-92jxl
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From                                                  Message
  ----     ------     ----                  ----                                                  -------
  Normal   Scheduled  5m26s                 default-scheduler                                     Successfully assigned devstats/devstats-grafana-cncf-b7f7c8446-p6hl9 to ip-192-168-13-57.us-east-2.compute.internal
  Normal   Pulling    3m7s (x4 over 5m25s)  kubelet, ip-192-168-13-57.us-east-2.compute.internal  pulling image "lukaszgryglicki/devstats-grafana"
  Normal   Pulled     3m6s (x4 over 5m24s)  kubelet, ip-192-168-13-57.us-east-2.compute.internal  Successfully pulled image "lukaszgryglicki/devstats-grafana"
  Normal   Created    3m6s (x4 over 5m24s)  kubelet, ip-192-168-13-57.us-east-2.compute.internal  Created container
  Normal   Started    3m6s (x4 over 5m24s)  kubelet, ip-192-168-13-57.us-east-2.compute.internal  Started container
  Warning  Unhealthy  2m37s (x4 over 5m7s)  kubelet, ip-192-168-13-57.us-east-2.compute.internal  Readiness probe failed:
  Warning  BackOff    17s (x14 over 4m16s)  kubelet, ip-192-168-13-57.us-east-2.compute.internal  Back-off restarting failed container
```

One provision-bootstrap failure:
```
$ k describe pod devstats-provision-bootstrap
Name:               devstats-provision-bootstrap
Namespace:          devstats
Priority:           0
PriorityClassName:  <none>
Node:               ip-192-168-13-57.us-east-2.compute.internal/192.168.13.57
Start Time:         Thu, 16 May 2019 11:09:04 -0700
Labels:             name=devstats
                    proj=bootstrap
                    type=boot
Annotations:        <none>
Status:             Failed
IP:                 192.168.1.147
Containers:
  devstats-provision-bootstrap:
    Container ID:  docker://68a42013889fe48b2bb1e93c82cc75f540ff4ee25348a2a111cb744bdf7a2b65
    Image:         lukaszgryglicki/devstats
    Image ID:      docker-pullable://lukaszgryglicki/devstats@sha256:7a69c55fa4c63b35007561a346620b267d08ebac41263643e99fa722bac9523c
    Port:          <none>
    Host Port:     <none>
    Command:
      ./devel/deploy_all.sh
    State:          Terminated
      Reason:       Error
      Exit Code:    100
      Started:      Thu, 16 May 2019 11:09:05 -0700
      Finished:     Thu, 16 May 2019 11:09:06 -0700
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  2Gi
    Requests:
      cpu:     200m
      memory:  256Mi
    Environment:
      INIT:                      1
      ONLYINIT:                  1
      WAITBOOT:                  15
      SKIPTEMP:                  1
      NOLOCK:                    1
      NOBACKUP:                  1
      SKIPADDALL:                1
      TEST_SERVER:               1
      UDROP:
      LDROP:
      NOCREATE:
      GHA2DB_NCPUS:
      GHA2DB_DEBUG:
      GHA2DB_CMDDEBUG:
      GHA2DB_GITHUB_DEBUG:
      GHA2DB_QOUT:
      GHA2DB_REPOS_DIR:
      GHA2DB_COMPANY_ACQ_YAML:   companies.yaml
      GHA2DB_PROJECTS_YAML:      projects.yaml
      GHA2DB_AFFILIATIONS_JSON:  github_users.json
      GHA2DB_COMPUTE_ALL:
      GHA2DB_SKIP_METRICS:
      GHA2DB_EXCLUDE_VARS:
      GHA2DB_ONLY_METRICS:
      GHA2DB_FORCE_PERIODS:
      PG_PORT:                   5432
      GHA2DB_GITHUB_OAUTH:       <set to the key 'GHA2DB_GITHUB_OAUTH.secret' in secret 'github-oauth'>  Optional: false
      PG_HOST:                   <set to the key 'PG_HOST.secret' in secret 'pg-db'>                     Optional: false
      PG_PASS:                   <set to the key 'PG_PASS.secret' in secret 'pg-db'>                     Optional: false
      PG_PASS_RO:                <set to the key 'PG_PASS_RO.secret' in secret 'pg-db'>                  Optional: false
      PG_PASS_TEAM:              <set to the key 'PG_PASS_TEAM.secret' in secret 'pg-db'>                Optional: false
      PG_ADMIN_USER:             <set to the key 'PG_ADMIN_USER.secret' in secret 'pg-db'>               Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-92jxl (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-92jxl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-92jxl
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age    From                                                  Message
  ----    ------     ----   ----                                                  -------
  Normal  Scheduled  8m25s  default-scheduler                                     Successfully assigned devstats/devstats-provision-bootstrap to ip-192-168-13-57.us-east-2.compute.internal
  Normal  Pulling    8m24s  kubelet, ip-192-168-13-57.us-east-2.compute.internal  pulling image "lukaszgryglicki/devstats"
  Normal  Pulled     8m24s  kubelet, ip-192-168-13-57.us-east-2.compute.internal  Successfully pulled image "lukaszgryglicki/devstats"
  Normal  Created    8m24s  kubelet, ip-192-168-13-57.us-east-2.compute.internal  Created container
  Normal  Started    8m24s  kubelet, ip-192-168-13-57.us-east-2.compute.internal  Started container
```

I'm assuming I need to make more changes to my values.yml?
